[package]
name = "bergamot-sys"
version = "0.1.0"
edition = "2024"

[features]
threads = []

[dependencies]

[build-dependencies]
cmake = "0.1"

[lib]
name = "bergamot_sys"
path = "src/lib.rs"

[[bin]]
name = "bergamot"
path = "src/bin/bergamot.rs"

[profile.release]
lto = "fat"
