[package]
name = "bergamot-sys"
version = "0.1.0"
edition = "2024"

[features]
threads = []

[dependencies]

[build-dependencies]
cmake = "0.1"

[[bin]]
name = "bergamot-example"
path = "src/main.rs"
